### ISSUE TITLE
where is the file 'data_train.dat'

### ISSUE THREAD

**Issue by andyyuan78** [lucastheis/trlda#1]
ubgpu@ubgpu:~/github/trlda$ python example.py 
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    for documents in load_documents('data_train.dat', 200):
  File "/usr/local/lib/python2.7/dist-packages/trlda/utils/load_documents.py", line 38, in document_generator
    with open(filepath) as handle:
IOError: [Errno 2] No such file or directory: 'data_train.dat'
ubgpu@ubgpu:~/github/trlda$

**Comment by lucastheis** [comment]
You will have to create your own or somehow obtain a dataset. The possible formats of the dataset are described here:

http://lucastheis.github.io/trlda/doc/trlda.utils-module.html#load_documents

Unfortunately I don't know any publicly available datasets that would already be in this format. I will see if I can create/upload one later.

**Comment by andyyuan78** [comment]
wait your datasets;)
